---
- hosts: civ_prod
  gather_facts: false
  vars:
    playbook_name: AnsVar
    ansible_host_key_checking: false 
    
  roles:
    - role: ansible-role-do_droplet
      environment: "{{digital_ocean_env}}"

